spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ayano2002
  thymeleaf:
    cache: false
  redis:
    host: 192.168.233.128
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 3
        max-wait: 3000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.Ayano
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl